name: virta-cd

env:
  "S3_BUCKET_NAME": "virta-bucket"
  "EBS_APPLICATION_NAME": "fuelingphp-laravel-prod"
  "EBS_ENVIRONMENT_NAME": "Fuelingphplaravelprod-env"
  "AWS_REGION": "us-east-1"
  "DEPLOY_PACKAGE_NAME": "laravel-app-${{github.sha}}.zip"
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
      - name: Clone the repository
      - uses: actions/checkout@v3
      
      - name: Zip the repository
        run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
